# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-24 19:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0002_auto_20161023_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='read',
            field=models.ManyToManyField(blank=True, to='blog.Post'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='subs',
            field=models.ManyToManyField(blank=True, to='blog.Blog'),
        ),
    ]
